version: '3.4'

services:
  postgres:
    image: postgres:11.2-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ${PWD}/postgresql_data:/var/lib/postgresql/data/pgdata

  sonarqube:
    build: ${PWD}/docker
    image: owasp/sonarqube
    environment:
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ${PWD}/sonarqube_data:/opt/sonarqube/data
      - ${PWD}/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
